############################################
# Starting local server
############################################
[tasks.dev_search]
dependencies = ["build_local"]
command = "npx"
args = ["-y", "pagefind", "--site", "dist", "--serve"]

[tasks.dev]
dependencies = ["fmt"]
command = "zola"
args = ["serve"]

############################################
# Local build
############################################
[tasks.build_local]
dependencies = ["fmt"]
command = "zola"
args = ["build"]

[tasks.build_zola]
command = "zola"
args = ["build"]

############################################
# Build for GitHub Actions
############################################
[tasks.build_gha]
dependencies = ["build_zola"]
command = "npx"
args = ["-y", "pagefind", "--site", "dist"]

############################################
# Check
############################################
[tasks.check]
dependencies = ["check_dprint", "check_djlint"]

############################################
# Format
############################################
[tasks.fmt]
dependencies = ["fmt_dprint", "fmt_djlint", "fmt_prettier"]

############################################
# Prettier
############################################
[tasks.fmt_prettier]
command = "npx"
args = ["prettier", "./sass", "--write"]

############################################
# https://dprint.dev
############################################
[tasks.install_dprint]
command = "cargo"
args = ["install", "dprint", "--locked"]

[tasks.fmt_dprint]
dependencies = ["install_dprint"]
command = "dprint"
args = ["--config", "dprint.json", "fmt"]

[tasks.check_dprint]
dependencies = ["install_dprint"]
command = "dprint"
args = ["--config", "dprint.json", "check"]

############################################
# https://djlint.com
############################################
[tasks.fmt_djlint]
command = "djlint"
args = [".", "--reformat"]

[tasks.check_djlint]
command = "djlint"
args = [".", "--check"]

############################################
# Wrangler CLI
############################################
# [tasks.wrangler_login]
# command = "npx"
# args = ["wrangler@latest", "login"]

# [tasks.wrangler_whoami]
# command = "npx"
# args = ["wrangler@latest", "whoami"]

############################################
# Pagefind
############################################
[tasks.indexing]
command = "npx"
args = ["-y", "pagefind", "--site", "dist"]
